### ISSUE TITLE
"Prompt Caching" 

### ISSUE THREAD

**Issue by lutprodic** [MMHK/bedrock-claude-proxy#1]
It would be great to eventually have the implementation for the latest "prompt caching" option released by Anthropic. 

https://www.anthropic.com/news/prompt-caching

https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching

**Comment by mm-sam** [comment]
Thank you for your suggestion regarding the latest "prompt caching" feature by Anthropic.

We are aware of this feature currently in beta testing. However, it appears that AWS Bedrock has not yet integrated this feature. Typically, models on AWS Bedrock lag behind the official release by one version. Based on previous experiences, such as with the tools use feature, we estimate that it may take another 1-2 months for this feature to be adopted, likely once it reaches RC (Release Candidate) status rather than being in beta.

Thank you for your understanding and patience.
